name: Python package

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade PIP
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Display Python version
        run: python3 --version

      - name: Display PIP version
        run: python3 -m pip --version

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements_tests.txt
          python3 -m pip install -r requirements_prod.txt

      - name: Test
        run: python3 -m pytest tests

      - name: Coverage
        run: python3 -m pytest --cov=. --cov-report=xml --cov-report=html tests

      - name: Upload coverage data
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          verbose: true
          fail_ci_if_error: true
